In [1]:
import numpy as np

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista)
print(array, type(array))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista)
print(array, type(array), array.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64


In [8]:
lista = [1, 2, 3, 4, 5]
type(lista), type(lista[0])

(list, int)

In [9]:
lista = [1, 2, 3, 4, 5.65]

array = np.array(lista)
print(array, type(array), array.dtype)

[1.   2.   3.   4.   5.65] <class 'numpy.ndarray'> float64


In [10]:
lista = [1, 2, 3, 4, 5.65, True]

array = np.array(lista)
print(array, type(array), array.dtype)

[1.   2.   3.   4.   5.65 1.  ] <class 'numpy.ndarray'> float64


In [11]:
lista = [1, 2, 3, 4, 5.65, True, "HELLO"]

array = np.array(lista)
print(array, type(array), array.dtype)

['1' '2' '3' '4' '5.65' 'True' 'HELLO'] <class 'numpy.ndarray'> <U32


In [14]:
lista = [1, 2, 3, 4, 5.65, True, "HELLO", ["HELLO", "WORLD"]]
lista
# array = np.array(lista)
# print(array, type(array), array.dtype)

[1, 2, 3, 4, 5.65, True, 'HELLO', ['HELLO', 'WORLD']]

In [19]:
lista = [["HELLO", "WORLD"], ["HELLO", "WORLD"]]
array = np.array(lista)
print(array, type(array), array.dtype)

[['HELLO' 'WORLD']
 ['HELLO' 'WORLD']] <class 'numpy.ndarray'> <U5


In [20]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista, dtype=np.int8)
print(array, type(array), array.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int8


In [21]:
2 ** 8 - 1

255

In [24]:
bin(255)

'0b11111111'

In [28]:
lista = [1, 2, 3, 4, 255]

array = np.array(lista, dtype=np.uint8)
print(array, type(array), array.dtype)

[  1   2   3   4 255] <class 'numpy.ndarray'> uint8


In [33]:
lista = [1, 2, 3, 4, -128] # 

array = np.array(lista, dtype=np.int8)
print(array, type(array), array.dtype)

[   1    2    3    4 -128] <class 'numpy.ndarray'> int8
