In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler


In [3]:
x  = np.array([-500.5, -100.1, 0, 100.1, 900.9])
x = x.reshape((-1, 1))
x

array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [4]:
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
x_scaled = minmax_scaler.fit_transform(x)
x_scaled


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [9]:
minmax_scaler = MinMaxScaler(feature_range=(0, 5))
x_scaled = minmax_scaler.fit_transform(x)
x_scaled.flatten()

array([0.        , 1.42857143, 1.78571429, 2.14285714, 5.        ])

In [8]:
minmax_scaler = MinMaxScaler(feature_range=(0, 5))
minmax_scaler.fit(x)
x_scaled =  minmax_scaler.transform(x)
x_scaled.flatten()

array([0.        , 1.42857143, 1.78571429, 2.14285714, 5.        ])

In [11]:
standard_scaler = StandardScaler()
x_standard = standard_scaler.fit_transform(x)
x_standard.flatten()

array([-1.26687088, -0.39316683, -0.17474081,  0.0436852 ,  1.79109332])

In [12]:
x_standard.mean()

np.float64(0.0)

In [13]:
# Standard deviation
x_standard.std()

np.float64(1.0)

In [15]:
robust = RobustScaler()
x_robust = robust.fit_transform(x)
x_robust.flatten()

array([-2.5, -0.5,  0. ,  0.5,  4.5])

In [16]:
x_standard.flatten()

array([-1.26687088, -0.39316683, -0.17474081,  0.0436852 ,  1.79109332])