In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 15, 22, 4, 100])
array


array([ 10,  20,  15,  22,   4, 100])

In [3]:
array + 11

array([ 21,  31,  26,  33,  15, 111])

In [5]:
lista = [10, 20, 15, 22, 4, 100]
lista + [11]

[10, 20, 15, 22, 4, 100, 11]

In [6]:
array 

array([ 10,  20,  15,  22,   4, 100])

In [ ]:
array < 30

array([ True,  True,  True,  True,  True, False])

In [ ]:
array [array  < 30 ]

array([10, 20, 15, 22,  4])

In [11]:
array

array([ 10,  20,  15,  22,   4, 100])

In [12]:
array % 2 == 0 

array([ True,  True, False,  True,  True,  True])

In [13]:
array % 2 != 0 

array([False, False,  True, False, False, False])

In [15]:
conditie1 = array  < 30
conditie2 = array % 2 == 0 

array[conditie1 & conditie2]



array([10, 20, 22,  4])