In [1]:
import numpy as np

In [3]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [4]:
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [5]:
np.random.randint(1, 100)

78

In [6]:
np.random.randint(1, 100, size=10)

array([83,  6, 29, 67, 75, 69, 10, 74, 57, 64])

In [7]:
np.random.randint(1, 100, size=10)

array([23,  1, 73, 51, 73, 73, 62, 98, 25, 65])

In [8]:
np.random.randint(1, 100, size=(3, 3))

array([[25, 38,  6],
       [67, 93, 23],
       [57, 12, 52]])

In [9]:
np.random.randint(1, 100, size=(3, 3, 2))

array([[[70, 22],
        [42, 24],
        [58, 92]],

       [[94, 74],
        [97, 19],
        [54, 86]],

       [[85, 69],
        [76, 18],
        [98, 46]]])