In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
from numpy import arange as range


range(5)

array([0, 1, 2, 3, 4])

In [4]:
list("Buna dimineata")

['B', 'u', 'n', 'a', ' ', 'd', 'i', 'm', 'i', 'n', 'e', 'a', 't', 'a']

In [5]:
# list = 300

In [6]:
arr = np.arange(3)
arr.dtype, type(arr)

(dtype('int64'), numpy.ndarray)

In [7]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [8]:
arr + arr

array([0, 2, 4])

In [9]:
list(arr) + list(arr)

[np.int64(0), np.int64(1), np.int64(2), np.int64(0), np.int64(1), np.int64(2)]

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) 
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr = [[ [1],[2],[3] ]]
np.squeeze(arr)

array([1, 2, 3])

In [16]:
arr = np.array([[ [1],[2],[3] ]])
arr.flatten()

array([1, 2, 3])

In [20]:
tp = [('name', 'U10'), ('price', 'float')]
tp = np.array(tp)

In [18]:
tp[1][1]

'float'

In [21]:
tp[1, 1]

np.str_('float')

In [ ]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
arr[ arr < 50 ]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
arr[ (arr < 50)  & (arr > 10) ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [26]:
arr[ (arr > 50)  | (arr < 10) ]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])